// Generated by https://quicktype.io

import { BaseResponse } from "../types/responses";

export interface GenerateAPIKeyData {
	id: number;
	user_id: number;
	name: string;
	key: string;
	created_at: string;
}

export interface GenerateAPIKeyResponse
	extends BaseResponse<GenerateAPIKeyData> {}
export interface ListAPIKeyResponse
	extends BaseResponse<GenerateAPIKeyData[]> {}
