// Validate ReCaptcha

import axios, { AxiosResponse } from "axios";
import { NextApiRequest, NextApiResponse } from "next";
// Generated by https://quicktype.io

export interface TurnstileAPIResponse {
	success: boolean;
	"error-codes": any[];
	challenge_ts: string;
	hostname: string;
	action: string;
	cdata: string;
	metadata: Metadata;
}

export interface Metadata {
	interactive: boolean;
}

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
	if (req.method !== "POST") {
		return res.status(405);
	}
	const secret = process.env.CLOUDFLARE_TURNSTILE_SITE_SECRET;
	if (!secret) {
		throw new Error("No CLOUDFLARE_TURNSTILE_SITE_SECRET set.");
	}
	const token = req.body.token;
	const response = await axios.post<any, AxiosResponse<TurnstileAPIResponse>>(
		`https://challenges.cloudflare.com/turnstile/v0/siteverify`,
		new URLSearchParams({
			secret,
			response: token,
		}),
		{
			headers: { "Content-Type": "application/x-www-form-urlencoded" },
		}
	);
	return res.send(response.data);
};
export default handler;
